---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: k8s-gitlab
  name: gitlab-redis-pvc
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: k8s-gitlab
  name: gitlab-postgresql-pvc
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: k8s-gitlab
  name: gitlab-pvc
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
