apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
  namespace: k8s-gitlab
  labels:
    name: gitlab
spec:
  serviceName: gitlab-https
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      name: gitlab
      labels:
        name: gitlab
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: sameersbn/gitlab:11.10.0
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: GITLAB_TIMEZONE
          value: Beijing
        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: long-and-random-alpha-numeric-string
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: long-and-random-alpha-numeric-string
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: long-and-random-alpha-numeric-string
        - name: GITLAB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: password
        - name: SMTP_ENABLED
          value: "true"
        - name: SMTP_DOMAIN
          value: linkingcities.com
        - name: SMTP_HOST
          value: smtp.mxhichina.com
        - name: SMTP_PORT
          value: "25"
        - name: SMTP_USER
          value: system.neo@linkingcities.com
        - name: SMTP_PASS
          value: yDQGVioHKdYB46
        - name: SMTP_STARTTLS
          value: "true"
        - name: SMTP_AUTHENTICATION
          value: login
       # - name: GITLAB_ROOT_EMAIL
       #   value: dewly_tg@163.com
        - name: GITLAB_HOST
          value: gitlab.21vianet.com
        #- name: GITLAB_HTTPS
        #  value: "true"
        #- name: SSL_SELF_SIGNED
        #  value: "true"
        #- name: SSL_CERTIFICATE_PATH
        #  value: "/home/git/data/certs/gitlab.crt"
        #- name: SSL_KEY_PATH
        #  value: "/home/git/data/certs/gitlab.key"
        #- name: SSL_DHPARAM_PATH
        #  value: "/home/git/data/certs/dhparam.pem"
        #- name: GITLAB_PORT
        #  value: "443"
        - name: GITLAB_PORT
          value: "80"
        - name: GITLAB_SSH_PORT
          value: "30022"
        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "true"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"
        - name: GITLAB_BACKUP_SCHEDULE
          value: daily
        - name: GITLAB_BACKUP_TIME
          value: 11:05
        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: passw0rd
        - name: DB_NAME
          value: gitlab_production
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        volumeMounts:
        - mountPath: /home/git/data
          name: data
        - mountPath: /home/git/data/backups
          name: backup
        - mountPath: /etc/localtime
          name: local-time
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 180
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gitlab-pvc
      - name: local-time
        hostPath:
          path: /etc/localtime
      - name: backup
        hostPath:
          path: /data/kubernetes/gitlab/backup
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: k8s-gitlab
  labels:
    name: gitlab
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: ssh
      port: 22
      targetPort: ssh
      nodePort: 30022
  type: NodePort
  selector:
    name: gitlab

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab
  namespace: k8s-gitlab
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: gitlab.21vianet.com
    http:
      paths:
      - backend:
          serviceName: gitlab
          servicePort: http
