apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab
  namespace: k8s-gitlab
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: gitlab.21vianet.com
    http:
      paths:
      - backend:
          serviceName: gitlab
          servicePort: http
