apiVersion: v1
kind: Pod
metadata:
  name: shared-volume-pod
  labels:
    app: shared-volume-pod
spec:
  containers:
  - name: alpine-write # 第一个容器模拟写日志
    image: alpine
    volumeMounts:
    - name: shared-volume
      mountPath: /var/log/app-logs # 容器内任意位置都行
      readOnly: false
    command:
      - sh
      - -c
      - "while true; do date +'%Y-%m-%d %H:%M:%S' >> /var/log/app-logs/log.log; sleep 1; done"
  - name: alpine-read # 第二个容器模拟收集日志
    image: alpine
    command: ["sh", "-c", "tail -f /var/log/collect-logs/log.log"]
    volumeMounts:
    - name: shared-volume
      mountPath: /var/log/collect-logs # 容器内任意位置都行
      readOnly: true
  volumes:
  - name: shared-volume # pod中有一个volume让其中的多个容器共享
    emptyDir: {}
