kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-data
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 20Gi
