apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: mysql
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
