apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: jenkins
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
# 这里其实就是为了获取certificate而已，上面创建的资源都没用，获取certificate后请删除deployment和service即可，只留下ingress
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-service-ingress
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - oss.21nmc.com
    secretName: nginx-tls
  rules:
  - host: oss.21nmc.com
    http:
      paths:
      - backend:
          #serviceName: nginx-service # 等获取证书后，再修改为cmdb-vue
          serviceName: cmdb-vue # 等获取证书后，再修改为cmdb-vue
          servicePort: 80
        path: /
